var prefferdPath = './voicemaker_preferred.dic'
var filterPath = './voicemaker_filter.dic'
var VoiceMaker = require('../build/default/voicemaker').VoiceMaker;
var voicemaker = new VoiceMaker();
voicemaker.setDictionary(prefferdPath, filterPath)
voicemaker.addPreferredWord('?','？')
voicemaker.addPreferredWord('；',',')
voicemaker.addPreferredWord('＋','プラス')
voicemaker.addPreferredWord('／','スラ')
voicemaker.addPreferredWord('@','アット')
voicemaker.addPreferredWord('＠','アット')
voicemaker.addPreferredWord('.','ドット')
voicemaker.addPreferredWord('．','ドット')
voicemaker.addPreferredWord('#','シャープ')
voicemaker.addPreferredWord('＃','シャープ')
voicemaker.addPreferredWord('$','ドル')
voicemaker.addPreferredWord('＄','ドル')
voicemaker.addPreferredWord('%','パーセント')
voicemaker.addPreferredWord('％','パーセント')
voicemaker.addPreferredWord('&','アンド')
voicemaker.addPreferredWord('＆','アンド')
voicemaker.addPreferredWord('=','イコール')
voicemaker.addPreferredWord('＝','イコール')
voicemaker.addPreferredWord('_','アンスコ')
voicemaker.addPreferredWord('＿','アンスコ')
voicemaker.addPreferredWord('＊','コメ')
voicemaker.addPreferredWord('*','コメ')
voicemaker.addPreferredWord('＊','コメ')
voicemaker.addPreferredWord('\\',',')
voicemaker.addPreferredWord('￥','エン')
voicemaker.addPreferredWord('|',',')
voicemaker.addPreferredWord('｜',',')
voicemaker.addPreferredWord('`',',')
voicemaker.addPreferredWord('｀',',')
voicemaker.addPreferredWord('"',',')
voicemaker.addPreferredWord('”',',')
voicemaker.addPreferredWord('“',',')
voicemaker.addPreferredWord('\'',',')
voicemaker.addPreferredWord('’',',')
voicemaker.addPreferredWord('‘',',')
voicemaker.addPreferredWord(':',',')
voicemaker.addPreferredWord('：',',')
voicemaker.addPreferredWord('!', ',')
voicemaker.addPreferredWord('！',',')
voicemaker.addPreferredWord('・',',')
voicemaker.addPreferredWord('　',',')
voicemaker.addPreferredWord('≪', '、')
voicemaker.addPreferredWord('≫', '、')
voicemaker.addPreferredWord('《', '、')
voicemaker.addPreferredWord('》', '、')
voicemaker.addPreferredWord('〔', '、')
voicemaker.addPreferredWord('〕', '、')
voicemaker.addPreferredWord('『', '、')
voicemaker.addPreferredWord('』', '、')
voicemaker.addPreferredWord('【', '、')
voicemaker.addPreferredWord('】', '、')
voicemaker.addPreferredWord('［', '、')
voicemaker.addPreferredWord('］', '、')
voicemaker.addPreferredWord('＜', '、')
voicemaker.addPreferredWord('＞', '、')
voicemaker.addPreferredWord('「', '、')
voicemaker.addPreferredWord('」', '、')
voicemaker.addPreferredWord('〈', '、')
voicemaker.addPreferredWord('〉', '、')
voicemaker.addPreferredWord('（', '、')
voicemaker.addPreferredWord('）', '、')
voicemaker.addPreferredWord('(', '、')
voicemaker.addPreferredWord(')', '、')
voicemaker.addPreferredWord('{', '、')
voicemaker.addPreferredWord('}', '、')
voicemaker.addPreferredWord('[', '、')
voicemaker.addPreferredWord(']', '、')
voicemaker.addPreferredWord('<', '、')
voicemaker.addPreferredWord('>', '、')
voicemaker.addPreferredWord('-----','00000')
voicemaker.delPreferredWord('-----')
voicemaker.addFilterWord('ゔぁ','バ')
voicemaker.addFilterWord('ゔァ','バ')
voicemaker.addFilterWord('ゔぃ','ビ')
voicemaker.addFilterWord('ゔィ','ビ')
voicemaker.addFilterWord('ゔぇ', 'べ')
voicemaker.addFilterWord('ゔェ', 'ベ')
voicemaker.addFilterWord('ゔぉ', 'ボ')
voicemaker.addFilterWord('ゔォ', 'ボ')
voicemaker.addFilterWord('ヴぁ','バ')
voicemaker.addFilterWord('ヴァ','バ')
voicemaker.addFilterWord('ヴぃ','ビ')
voicemaker.addFilterWord('ヴィ','ビ')
voicemaker.addFilterWord('ヴぇ', 'べ')
voicemaker.addFilterWord('ヴェ', 'ベ')
voicemaker.addFilterWord('ヴぉ', 'ボ')
voicemaker.addFilterWord('ヴォ', 'ボ')
voicemaker.addFilterWord('ゔ', 'ブ')
voicemaker.addFilterWord('ヴ', 'ブ')
voicemaker.addFilterWord('づ', 'ズ')
voicemaker.addFilterWord('ヅ', 'ズ')
voicemaker.addFilterWord('ぁ', 'ア')
voicemaker.addFilterWord('ぃ', 'イ')
voicemaker.addFilterWord('ぅ', 'ウ')
voicemaker.addFilterWord('ぇ', 'エ')
voicemaker.addFilterWord('ぉ', 'オ')
voicemaker.addFilterWord('き', 'キ')
voicemaker.addFilterWord('し', 'シ')
voicemaker.addFilterWord('ひ', 'ヒ')
voicemaker.addFilterWord('に', 'ニ')
voicemaker.addFilterWord('み', 'ミ')
voicemaker.addFilterWord('り', 'リ')
voicemaker.addFilterWord('ぎ', 'ギ')
voicemaker.addFilterWord('じ', 'ジ')
voicemaker.addFilterWord('び', 'ビ')
voicemaker.addFilterWord('ぴ', 'ビ')
voicemaker.addFilterWord('ゃ', 'ャ')
voicemaker.addFilterWord('ゅ', 'ュ')
voicemaker.addFilterWord('ょ', 'ョ')
voicemaker.addFilterWord('?','？')
voicemaker.addFilterWord('；',',')
voicemaker.addFilterWord('＋','プラス')
voicemaker.addFilterWord('／','スラ')
voicemaker.addFilterWord('@','アット')
voicemaker.addFilterWord('＠','アット')
voicemaker.addFilterWord('.','ドット')
voicemaker.addFilterWord('．','ドット')
voicemaker.addFilterWord('#','シャープ')
voicemaker.addFilterWord('＃','シャープ')
voicemaker.addFilterWord('$','ドル')
voicemaker.addFilterWord('＄','ドル')
voicemaker.addFilterWord('%','パーセント')
voicemaker.addFilterWord('％','パーセント')
voicemaker.addFilterWord('&','アンド')
voicemaker.addFilterWord('＆','アンド')
voicemaker.addFilterWord('=','イコール')
voicemaker.addFilterWord('＝','イコール')
voicemaker.addFilterWord('_','アンスコ')
voicemaker.addFilterWord('＿','アンスコ')
voicemaker.addFilterWord('＊','コメ')
voicemaker.addFilterWord('*','コメ')
voicemaker.addFilterWord('＊','コメ')
voicemaker.addFilterWord('\\',',')
voicemaker.addFilterWord('￥','エン')
voicemaker.addFilterWord('|',',')
voicemaker.addFilterWord('｜',',')
voicemaker.addFilterWord('`',',')
voicemaker.addFilterWord('｀',',')
voicemaker.addFilterWord('"',',')
voicemaker.addFilterWord('”',',')
voicemaker.addFilterWord('“',',')
voicemaker.addFilterWord('\'',',')
voicemaker.addFilterWord('’',',')
voicemaker.addFilterWord('‘',',')
voicemaker.addFilterWord(':',',')
voicemaker.addFilterWord('：',',')
voicemaker.addFilterWord('!', ',')
voicemaker.addFilterWord('！',',')
voicemaker.addFilterWord('・',',')
voicemaker.addFilterWord('　',',')
voicemaker.addFilterWord('≪', '、')
voicemaker.addFilterWord('≫', '、')
voicemaker.addFilterWord('《', '、')
voicemaker.addFilterWord('》', '、')
voicemaker.addFilterWord('〔', '、')
voicemaker.addFilterWord('〕', '、')
voicemaker.addFilterWord('『', '、')
voicemaker.addFilterWord('』', '、')
voicemaker.addFilterWord('【', '、')
voicemaker.addFilterWord('】', '、')
voicemaker.addFilterWord('［', '、')
voicemaker.addFilterWord('］', '、')
voicemaker.addFilterWord('＜', '、')
voicemaker.addFilterWord('＞', '、')
voicemaker.addFilterWord('「', '、')
voicemaker.addFilterWord('」', '、')
voicemaker.addFilterWord('〈', '、')
voicemaker.addFilterWord('〉', '、')
voicemaker.addFilterWord('（', '、')
voicemaker.addFilterWord('）', '、')
voicemaker.addFilterWord('(', '、')
voicemaker.addFilterWord(')', '、')
voicemaker.addFilterWord('{', '、')
voicemaker.addFilterWord('}', '、')
voicemaker.addFilterWord('[', '、')
voicemaker.addFilterWord(']', '、')
voicemaker.addFilterWord('<', '、')
voicemaker.addFilterWord('>', '、')
voicemaker.addFilterWord('A', 'エイ')
voicemaker.addFilterWord('B', 'ビー')
voicemaker.addFilterWord('C', 'シー')
voicemaker.addFilterWord('D', 'ディー')
voicemaker.addFilterWord('E', 'イー')
voicemaker.addFilterWord('F', 'エフ')
voicemaker.addFilterWord('G', 'ジー')
voicemaker.addFilterWord('H', 'エッチ')
voicemaker.addFilterWord('I', 'アイ')
voicemaker.addFilterWord('J', 'ジェー')
voicemaker.addFilterWord('K', 'ケイ')
voicemaker.addFilterWord('L', 'エル')
voicemaker.addFilterWord('M', 'エム')
voicemaker.addFilterWord('N', 'エヌ')
voicemaker.addFilterWord('O', 'オー')
voicemaker.addFilterWord('P', 'ピー')
voicemaker.addFilterWord('Q', 'キュー')
voicemaker.addFilterWord('R', 'アール')
voicemaker.addFilterWord('S', 'エス')
voicemaker.addFilterWord('T', 'ティー')
voicemaker.addFilterWord('U', 'ユー')
voicemaker.addFilterWord('V', 'ブイ')
voicemaker.addFilterWord('W', 'ダブリュー')
voicemaker.addFilterWord('X', 'エックス')
voicemaker.addFilterWord('Y', 'ワイ')
voicemaker.addFilterWord('Z', 'ゼット')
voicemaker.addFilterWord('ほげ', 'ほげげ')
voicemaker.delFilterWord('ほげ')
voicemaker.saveDictionary()
voicemaker.loadDictionary()
var VoiceMaker = require('../build/default/voicemaker').VoiceMaker;
var voicemaker = new VoiceMaker();
voicemaker.setDictionary(prefferdPath, filterPath)
voicemaker.loadDictionary()
voicemaker.loadDictionary()
voicemaker.convert('私は、モモンガの次男の孫の長男の従兄弟のへべれけという者です。');
voicemaker.convert('私は、モモンガの次男の孫の長男の従兄弟のへべれけという者です。', '/usr/local/share/aquestalk2/phont/aq_rm.phont');
voicemaker.convert('私は、モモンガの次男の孫の長男の従兄弟のへべれけという者です。', 80, '/usr/local/share/aquestalk2/phont/aq_rm.phont');
voicemaker.convert('ジオンガ', 80, '/usr/local/share/aquestalk2/phont/aq_rm.phont');
voicemaker.convert('ってってってーってってってて', 80, '/usr/local/share/aquestalk2/phont/aq_rm.phont');
voicemaker.convert('ヴ', 80, '/usr/local/share/aquestalk2/phont/aq_rm.phont');
voicemaker.convert('なんだってー！そんなヴぁかなー', 80, '/usr/local/share/aquestalk2/phont/aq_rm.phont');
voicemaker.convert('づづづづづづ、なんだってー！そんなゔぁかなー', 80, '/usr/local/share/aquestalk2/phont/aq_rm.phont');
voicemaker.convert('あ い　う　え　お　 か き く', 80, '/usr/local/share/aquestalk2/phont/aq_rm.phont');
voicemaker.convert('あああ　ううう', 80, '/usr/local/share/aquestalk2/phont/aq_rm.phont');
voicemaker.convert('', 80,'/usr/local/share/aquestalk2/phont/aq_rm.phont');
voicemaker.convert('かかかか・おあ\'えお,こ', 80, '/usr/local/share/aquestalk2/phont/aq_rm.phont');
voicemaker.convert('≪≫あ〔〕『』【】［］()<>{}＜＞「」〈〉[]《》', 80, '/usr/local/share/aquestalk2/phont/aq_rm.phont');
voicemaker.convert('30年以上に及ぶキャリアの中で、かつては果樹園が広がるのどかな土地で', 80, '/usr/local/share/aquestalk2/phont/aq_rm.phont');
voicemaker.convert('ジョブズ氏は、30年以上に及ぶキャリアの中で、かつては果樹園が広がるのどかな土地であったシリコンバレーを（情報技術）業界のイノベーションの中心地へと変ぼうさせる上で大いに貢献した。', 80, '/usr/local/share/aquestalk2/phont/aq_rm.phont');
voicemaker.convert('<NUM VAL=3512>の/はーどでぃ\'_ス_クに、<NUMK VAL=2006 COUNTER=ねん>、<NUMK VAL=1 COUNTER=がつ>;<NUMK VAL=15 COUNTER=にち>', 80, '/usr/local/share/aquestalk2/phont/aq_rm.phont');
voicemaker.convert('いおjg；えをいjg；wj；おえjwごいめw；いvm；うぇm；おあうぇいjg；おえうぃjぐぁ', 80, '/usr/local/share/aquestalk2/phont/aq_rm.phont');
voicemaker.convert('１０１回', 80,'/usr/local/share/aquestalk2/phont/aq_rm.phont');
voicemaker.convert('おwぺkfwぺおkg：えw', 80,'/usr/local/share/aquestalk2/phont/aq_rm.phont');
voicemaker.convert('ubuntu 11/b00', 80,'/usr/local/share/aquestalk2/phont/aq_rm.phont');
voicemaker.convert('ubuntu 11/00', 80,'/usr/local/share/aquestalk2/phont/aq_rm.phont');
voicemaker.convert('ubuntu 11.00', 80,'/usr/local/share/aquestalk2/phont/aq_rm.phont');
