var VoiceMaker = require('../build/default/voicemaker').VoiceMaker;
var voicemaker = new VoiceMaker();
console.log(voicemaker.convert("私は、モモンガの次男の孫の長男の従兄弟のへべれけという者です。"));
console.log(voicemaker.convert("私は、モモンガの次男の孫の長男の従兄弟のへべれけという者です。", "/usr/local/share/aquestalk2/phont/aq_rm.phont"));
console.log(voicemaker.convert("私は、モモンガの次男の孫の長男の従兄弟のへべれけという者です。", 80, "/usr/local/share/aquestalk2/phont/aq_rm.phont"));
console.log(voicemaker.convert("ジオンガ", 80, "/usr/local/share/aquestalk2/phont/aq_rm.phont"));
console.log(voicemaker.convert("ってってってーってってってて", 80, "/usr/local/share/aquestalk2/phont/aq_rm.phont"));
console.log(voicemaker.convert("づづづづづづ、なんだってー！そんなゔぁかなー", 80, "/usr/local/share/aquestalk2/phont/aq_rm.phont"));
console.log(voicemaker.convert("あ い　う　え　お　 か き く", 80, "/usr/local/share/aquestalk2/phont/aq_rm.phont"));
console.log(voicemaker.convert("あああ　ううう", 80, "/usr/local/share/aquestalk2/phont/aq_rm.phont"));
console.log(voicemaker.convert("", 80, "/usr/local/share/aquestalk2/phont/aq_rm.phont"));
